apiVersion: v1
kind: Namespace
metadata:
  name: unbury
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbury
  namespace: unbury
  labels:
    app.kubernetes.io/name: unbury
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbury
  template:
    metadata:
      labels:
        app: unbury
    spec:
      containers:
        - name: app
          image: joaquinrodriguez/unbury
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
---

apiVersion: v1
kind: Service
metadata:
  name: unbury
  namespace: unbury
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: unbury
